"""纯函数层：零 SDK 依赖、零 IO。

- `catalog`：表情包条目的数据形状、图片格式嗅探、检索与目录文案（给模型看的）。
- `configuration`：`[sticker_manager]` 配置族的 dataclass 视图与默认值。
- `pack`：套图包的 manifest 协议与 zip 条目名安全门（v0.2.0）。
- `awareness`：存在感注入的选内容与拼文案（v0.2.0）。
"""

from .awareness import build_awareness_text, pick_recent
from .catalog import (
    CAPTION_MAX_CHARS,
    DEFAULT_ZONE_NAME,
    DESC_MAX_CHARS,
    GROUP_DESC_MAX_CHARS,
    GROUP_MAX_CHARS,
    MAX_STICKER_BYTES,
    OFFICIAL_PACK_RELPATH,
    OFFICIAL_ZONE_NAME,
    PREVIEW_CHUNK_BYTES,
    SEND_CANDIDATES_MAX,
    UPLOAD_CHUNK_BYTES,
    UPLOAD_MAX_TOTAL_BYTES,
    VISIBLE_TEXT_MAX_CHARS,
    ZONE_MAX_CHARS,
    Sticker,
    content_sha256,
    desc_from_filename,
    detect_image_format,
    format_catalog_for_model,
    format_group_overview,
    new_sticker_id,
    new_zone_id,
    normalize_group,
    normalize_optional_text,
    normalize_tags,
    normalize_zone_name,
    parse_tags_field,
    resolve_send_target,
    search_stickers,
    search_with_scores,
    validate_desc,
    validate_desc_optional,
    validate_optional_text,
)
from .configuration import (
    EAGERNESS_DEFAULT,
    EAGERNESS_LEVELS,
    AwarenessSettings,
    SendSettings,
    StickerManagerSettings,
    StorageSettings,
)
from .eagerness import injection_guidance, normalize_tier, send_tool_description
from .labeling import LabelRefresh, index_by_digest, plan_label_refresh
from .pack import (
    PACK_DIR_PREFIX,
    PACK_MANIFEST_FILENAME,
    PACK_MANIFEST_VERSION,
    PACK_MAX_ENTRIES,
    PackEntry,
    build_manifest,
    pack_entry_from_raw,
    parse_manifest,
    parse_manifest_groups,
    parse_pack_version,
    safe_member_name,
    sticker_to_manifest_entry,
)

__all__ = [
    "CAPTION_MAX_CHARS",
    "DESC_MAX_CHARS",
    "GROUP_DESC_MAX_CHARS",
    "GROUP_MAX_CHARS",
    "MAX_STICKER_BYTES",
    "PACK_DIR_PREFIX",
    "PACK_MANIFEST_FILENAME",
    "PACK_MANIFEST_VERSION",
    "PACK_MAX_ENTRIES",
    "PACK_VERSION_KEY",
    "PREVIEW_CHUNK_BYTES",
    "SEND_CANDIDATES_MAX",
    "UPLOAD_CHUNK_BYTES",
    "UPLOAD_MAX_TOTAL_BYTES",
    "VISIBLE_TEXT_MAX_CHARS",
    "ZONE_MAX_CHARS",
    "DEFAULT_ZONE_NAME",
    "EAGERNESS_DEFAULT",
    "EAGERNESS_LEVELS",
    "OFFICIAL_PACK_RELPATH",
    "OFFICIAL_ZONE_NAME",
    "AwarenessSettings",
    "LabelRefresh",
    "PackEntry",
    "SendSettings",
    "Sticker",
    "StorageSettings",
    "StickerManagerSettings",
    "build_awareness_text",
    "build_manifest",
    "content_sha256",
    "desc_from_filename",
    "detect_image_format",
    "format_catalog_for_model",
    "format_group_overview",
    "injection_guidance",
    "index_by_digest",
    "new_sticker_id",
    "new_zone_id",
    "normalize_group",
    "normalize_tier",
    "normalize_zone_name",
    "normalize_optional_text",
    "normalize_tags",
    "pack_entry_from_raw",
    "parse_manifest",
    "parse_manifest_groups",
    "parse_pack_version",
    "parse_tags_field",
    "pick_recent",
    "plan_label_refresh",
    "resolve_send_target",
    "safe_member_name",
    "send_tool_description",
    "search_stickers",
    "search_with_scores",
    "sticker_to_manifest_entry",
    "validate_desc",
    "validate_desc_optional",
    "validate_optional_text",
]
